---
name: updatecli

on:
  # Allow to be run manually
  workflow_dispatch:
  schedule:
    # Run once per week (to avoid alert fatigue)
    - cron: '0 2 * * 1' # Every monday at 2am UTC
  push:
  pull_request:
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: tibdex/github-app-token@v1.5
        id: generate_token
        with:
          app_id: ${{ secrets.JENKINS_ADMIN_APP_ID }}
          private_key: ${{ secrets.JENKINS_ADMIN_APP_PRIVKEY }}

      - name: Diff
        continue-on-error: true
        uses: updatecli/updatecli-action@v1
        with:
          command: diff
          flags: "--config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml"
        env:
          # Github "generated" token is used because the repository secrets are not available in PRs.
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Apply
        uses: updatecli/updatecli-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          command: apply
          flags: "--config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml"
        env:
          # Secret repository's token is used to create PRs on behalf of the jenkins-infra-bot
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
